import type { AuditFacts, Finding, FindingLevel, ReadinessScore } from '../types';
import { categoryLevers } from './score';

/**
 * The exportable form of an audit.
 *
 * This is what leaves the tool and lands in a ticket, so it has to stand on its
 * own: what was measured, how, and the caveat that the fetch was simulated.
 * A finding pasted without that caveat could send someone chasing a difference
 * that only exists because the request came from a residential IP.
 */

export interface ReportInput {
  facts: AuditFacts;
  findings: Finding[];
  score: ReadinessScore;
  at: number;
}

const LEVEL_HEADINGS: Record<FindingLevel, string> = {
  critical: 'Critical',
  warning: 'Warnings',
  notice: 'Opportunities',
  good: 'Working well',
};

const LEVEL_SEQUENCE: FindingLevel[] = ['critical', 'warning', 'notice', 'good'];

export function toMarkdown({ facts, findings, score, at }: ReportInput): string {
  const lines: string[] = [];
  const date = new Date(at).toISOString().slice(0, 10);

  lines.push(`# Agent readiness — ${facts.url}`);
  lines.push('');
  lines.push(
    `Audited as **${facts.profileName}** on ${date}. Score **${score.overall}/100** — ${score.verdict}.`,
  );
  lines.push('');
  lines.push(
    '> Simulated agent fetch: the request carried a crawler User-Agent but came from a residential IP and was unsigned. An edge that verifies bots by reverse DNS may answer a real crawler differently.',
  );
  lines.push('');

  lines.push('## Scores');
  lines.push('');
  lines.push('| Category | Score | Weight |');
  lines.push('| --- | --- | --- |');
  for (const category of score.categories) {
    // An unevaluated category must never read as a perfect one.
    const value = category.evaluated ? `${category.score}/100` : 'not evaluated';
    const weight = category.evaluated ? `${category.weight}%` : '—';
    lines.push(`| ${category.label} | ${value} | ${weight} |`);
  }
  if (score.categories.some((c) => !c.evaluated)) {
    lines.push('');
    lines.push(
      '_Categories marked "not evaluated" had no document to measure — the agent never received one — and are excluded from the overall score rather than counted as passing._',
    );
  }
  lines.push('');

  // Only categories with room to improve. A category at full marks needs no
  // advice in a ticket, and all five with every lever would bury the findings.
  const improvable = score.categories.filter((c) => c.evaluated && c.score < 100);
  if (improvable.length > 0) {
    lines.push('### What moves each score');
    for (const category of improvable) {
      lines.push('');
      lines.push(`**${category.label}** — ${category.score}/100`);
      lines.push('');
      for (const lever of categoryLevers(category.category)) {
        lines.push(`- ${lever}`);
      }
    }
    lines.push('');
  }

  lines.push('## Findings');
  for (const level of LEVEL_SEQUENCE) {
    const group = findings.filter((f) => f.level === level);
    if (group.length === 0) continue;
    lines.push('');
    lines.push(`### ${LEVEL_HEADINGS[level]}`);
    lines.push('');
    for (const finding of group) {
      const cost = finding.points > 0 ? ` _(−${finding.points} ${finding.category})_` : '';
      lines.push(`- **${finding.title}**${cost}`);
      lines.push(`  ${finding.evidence}`);
      if (finding.fix) lines.push(`  _Fix:_ ${finding.fix}`);
    }
  }
  lines.push('');

  lines.push('## What each client received');
  lines.push('');
  lines.push('| Document | Status | Words | Content tokens | Payload tokens |');
  lines.push('| --- | --- | --- | --- | --- |');
  const rows = [
    ['What you see', facts.rendered],
    ['Raw HTML (browser)', facts.raw],
    [facts.profileName, facts.agent],
  ] as const;
  for (const [label, doc] of rows) {
    if (!doc) {
      lines.push(`| ${label} | not captured | — | — | — |`);
      continue;
    }
    lines.push(
      `| ${label} | ${doc.status || '—'} | ${num(doc.metrics.words)} | ${num(doc.metrics.tokens)} | ${num(doc.metrics.payloadTokens)} |`,
    );
  }
  lines.push('');

  const blocked = facts.access.verdicts.filter((v) => !v.verdict.allowed);
  lines.push('## robots.txt');
  lines.push('');
  if (!facts.access.robots) {
    lines.push('No robots.txt rules apply to this origin — every crawler is allowed everywhere.');
  } else if (blocked.length === 0) {
    lines.push('Every crawler profile is allowed on this path.');
  } else {
    lines.push('Blocked on this path:');
    lines.push('');
    for (const row of blocked) {
      lines.push(`- **${row.name}** — ${row.verdict.reason}`);
    }
  }
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('Generated by ViewAsAgent.');

  return lines.join('\n');
}

export function toJson({ facts, findings, score, at }: ReportInput): string {
  return JSON.stringify(
    {
      tool: 'ViewAsAgent',
      auditedAt: new Date(at).toISOString(),
      url: facts.url,
      agent: facts.profileName,
      simulated: true,
      score,
      findings,
      gaps: facts.gaps,
      access: facts.access,
      documents: {
        rendered: facts.rendered && summarize(facts.rendered),
        rawBrowser: summarize(facts.raw),
        rawAgent: summarize(facts.agent),
      },
      structured: facts.structured,
    },
    null,
    2,
  );
}

function summarize(doc: AuditFacts['raw']) {
  return {
    label: doc.label,
    url: doc.url,
    status: doc.status,
    contentType: doc.contentType,
    shape: doc.shape,
    title: doc.title,
    metrics: doc.metrics,
    headings: doc.headings,
  };
}

/** A filename that sorts by date and says which page it covers. */
export function reportFilename(facts: AuditFacts, at: number, extension: string): string {
  let host = 'page';
  let path = '';
  try {
    const url = new URL(facts.url);
    host = url.hostname.replace(/^www\./, '');
    path = url.pathname.replace(/\/+$/, '').replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '');
  } catch {
    // Fall back to the defaults.
  }
  const date = new Date(at).toISOString().slice(0, 10);
  const agent = facts.profileName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return [host, path, agent, date].filter(Boolean).join('-') + extension;
}

function num(value: number): string {
  return value.toLocaleString('en-US');
}
